### ISSUE TITLE
Setting airflow generates an nonetype error

### ISSUE THREAD

**Issue by mflage** [aglehmann/home_assistant_ecovent#11]
I'm attempting to call the service to set the airflow mode, but this generates the following error in the home assistant logs:

```
2021-01-31 17:08:24 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140318266675648] 'NoneType' object has no attribute 'set_airflow'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1484, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ecovent/fan.py", line 84, in service_handle
    fan_device.set_airflow(airflow)
AttributeError: 'NoneType' object has no attribute 'set_airflow'
```

Turning the fan on and off and also changing the speed of it works just fine. Looking at the code I see that this attempts to get the fan device by doing the following:

```python
        fan_device = next(
                (fan for fan in hass.data[ECOVENT_FAN_DEVICES] if fan.entity_id == entity_id),
            None,
        )
```

Evidently this doesn't return anything, so instead None is returned here. Could it be an issue with the fan.entity_id == entity_id check?

**Comment by aglehmann** [comment]
That seems like a plausible explanation indeed. The only way I am able to re-produce this behavior is by entering the wrong "entity_id" when calling the service "fan.ecovent_set_airflow". I'm not sure there is a way to actually test wether or not a user enters a valid "entity_id" in HA, but it seems that an incorrect "entity_id" is causing the error you are experiencing.

**Comment by mflage** [comment]
Ah, of course. *blush* you can go ahead and close this issue :)
