### ISSUE TITLE
core-2021.10.5 - Error while setting up ecovent platform for fan

### ISSUE THREAD

**Issue by benjaminaker** [aglehmann/home_assistant_ecovent#19]
I'm not sure where to start looking on this issue, but it seems like the plugin has stopped working after HA core-2021.10.5. My system worked fine before the update, and my devices are accessible in my other non-HA integrations.

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/ecovent/fan.py", line 71, in async_setup_platform
hass.data[ECOVENT_FAN_DEVICES].append(EcoventFan(device))
File "/config/custom_components/ecovent/fan.py", line 100, in __init__
self._fan.update()
File "/usr/local/lib/python3.9/site-packages/ecovent/__init__.py", line 43, in update
response = self.receive()
File "/usr/local/lib/python3.9/site-packages/ecovent/__init__.py", line 36, in receive
response = self.socket.recv(98)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by benjaminaker** [comment]
Hi, so sorry, I missed the notification on this. Thanks for the reply! I've updated the HA system quite a few times since then, and suddenly one of my Twinfresh units started to respond again, like nothing had happened. 

The weird thing is that they all work in the Twinfresh app, but only one of four works in the HA integration. All static IPs etc.
But then at least I think we can close this thread, no bug to see here, move along..

Again, thanks for your time!
