### ISSUE TITLE
Error on changing airflow

### ISSUE THREAD

**Issue by robinostlund** [aglehmann/home_assistant_ecovent#5]
Hi,
I get this error when i try to change the airflow:
2020-04-14 11:57:30 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139853161977360] name 'fan' is not defined
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1232, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1255, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 207, in service_handler
    await script.async_turn_on(variables=service.data, context=service.context)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 284, in async_turn_on
    await self.script.async_run(kwargs.get(ATTR_VARIABLES), context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 802, in async_run
    await run.async_run()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 523, in async_run
    await self._async_run()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 540, in _async_run
    await self._async_step(log_exceptions=not propagate_exceptions)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 154, in _async_step
    self, f"_async_{cv.determine_script_action(self._action)}_step"
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 624, in _async_call_service_step
    *self._prep_call_service_step(), blocking=True, context=self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1232, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1259, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ecovent/fan.py", line 77, in service_handle
    fan.set_airflow(airflow)
NameError: name 'fan' is not defined

Cannot see that fan is defined in the service_handle.

Brg
Robin

**Comment by aglehmann** [comment]
Hi,
Thank for reporting this issue, it should be resolved now.
There were some internal changes in HA which caused this and I haven't been paying attention.
Please let me know if you still have issues.

Regards,
Aleksander

**Comment by robinostlund** [comment]
Awesome it works :) thanks for a great component, just want to say that it also works for Nibe DVC 10-50W fans :)
